# Generated by Django 3.2 on 2022-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tap',
            name='url_label',
            field=models.CharField(default='default url_label', help_text='text for displaying in link label', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tap',
            name='description',
            field=models.CharField(help_text='\n            extended description of what the link is about or,what kinds\n            of information is found at url, or what is the importance of\n            the link\n        ', max_length=400, verbose_name='extended description'),
        ),
        migrations.AlterField(
            model_name='tap',
            name='title',
            field=models.CharField(help_text='short title for the url item', max_length=200),
        ),
    ]
