# Generated by Django 3.2 on 2022-04-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0002_auto_20220401_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='tap',
            name='url',
            field=models.URLField(default='http://localhost:8000/', help_text='url of page which has content of interest for accessiblity'),
        ),
    ]
