# Generated by Django 3.2 on 2022-04-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0004_alter_tap_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tap',
            options={'ordering': ['-id']},
        ),
    ]
