# Generated by Django 3.2 on 2022-04-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0008_auto_20220421_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tap',
            name='title',
        ),
    ]
