# Generated by Django 4.0 on 2022-04-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0011_alter_tap_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tap',
            name='description',
            field=models.TextField(blank=True, default='', help_text='\n            extended description of what the link is about or,what kinds\n            of information is found at url, or what is the importance of\n            the link\n        ', verbose_name='extended description'),
        ),
    ]
