# Generated by Django 4.0 on 2022-04-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0012_alter_tap_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tap',
            name='description',
            field=models.TextField(help_text='\n            extended description of what the link is about or,what kinds\n            of information is found at url, or what is the importance of\n            the link\n        ', verbose_name='extended description'),
        ),
        migrations.AlterField(
            model_name='tap',
            name='url_label',
            field=models.CharField(blank=True, default='', help_text='text for displaying in link label', max_length=200),
        ),
    ]
