# Generated by Django 4.0 on 2022-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0014_alter_tap_description_alter_tap_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tap',
            name='description',
            field=models.TextField(help_text='\n            extended description of what the link is about or,what kinds\n            of information is found at url, or what is the importance of\n            the link\n        ', verbose_name='extended description'),
        ),
        migrations.AlterField(
            model_name='tap',
            name='url',
            field=models.URLField(blank=True, help_text='url of page which has content of interest for accessiblity'),
        ),
    ]
